version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db

  db:
  # it's a dirty build, so we don't need to have data percistence in volume
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
